name: Input Test (temporary)

on:
  workflow_dispatch:
    inputs:
      temperature:
        description: "test"
        required: false
        default: "0.3"
      num_tests:
        description: "test"
        required: false
        default: "2"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEMPERATURE: ${{ inputs.temperature }}
      NUM_TESTS: ${{ inputs.num_tests }}
    steps:
      - run: echo "TEMPERATURE=[${TEMPERATURE}] NUM_TESTS=[${NUM_TESTS}]"
